// <auto-generated />
namespace NTPT_1821050973.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202106051634252_SV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
