// <auto-generated />
namespace NTPT_1821050973.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SV2));
        
        string IMigrationMetadata.Id
        {
            get { return "202106051658118_SV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
